// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookVerse.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251122142100_AddedTimestamps")]
    partial class AddedTimestamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookVerse.Api.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(4957),
                            CreatedBy = "System",
                            FirstName = "George",
                            LastName = "Orwell",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(4960),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(4966),
                            CreatedBy = "System",
                            FirstName = "J.K.",
                            LastName = "Rowling",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(4966),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(4968),
                            CreatedBy = "System",
                            FirstName = "Jane",
                            LastName = "Austen",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(4968),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(4969),
                            CreatedBy = "System",
                            FirstName = "Mark",
                            LastName = "Twain",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(4970),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(4971),
                            CreatedBy = "System",
                            FirstName = "Fyodor",
                            LastName = "Dostoevsky",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(4971),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("BookVerse.Api.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PublishDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5125),
                            CreatedBy = "System",
                            Price = 15.99m,
                            PublishDate = new DateOnly(1949, 6, 8),
                            Title = "1984",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5126),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5130),
                            CreatedBy = "System",
                            Price = 19.99m,
                            PublishDate = new DateOnly(1997, 6, 26),
                            Title = "Harry Potter and the Sorcerer's Stone",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5130),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 3,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5132),
                            CreatedBy = "System",
                            Price = 12.5m,
                            PublishDate = new DateOnly(1813, 1, 28),
                            Title = "Pride and Prejudice",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5132),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CategoryId = 4,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5135),
                            CreatedBy = "System",
                            Price = 14.2m,
                            PublishDate = new DateOnly(1884, 12, 10),
                            Title = "Adventures of Huckleberry Finn",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5135),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CategoryId = 5,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5136),
                            CreatedBy = "System",
                            Price = 17.75m,
                            PublishDate = new DateOnly(1866, 1, 1),
                            Title = "Crime and Punishment",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5137),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("BookVerse.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5171),
                            CreatedBy = "System",
                            Name = "Dystopian",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5172),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5203),
                            CreatedBy = "System",
                            Name = "Fantasy",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5204),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5205),
                            CreatedBy = "System",
                            Name = "Classic",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5206),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5207),
                            CreatedBy = "System",
                            Name = "Adventure",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5207),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5208),
                            CreatedBy = "System",
                            Name = "Philosophical Fiction",
                            UpdatedAtUtc = new DateTime(2025, 11, 22, 14, 20, 59, 550, DateTimeKind.Utc).AddTicks(5209),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("BookVerse.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3472507d-6568-4360-bbaa-da29673194f5"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("f27ed6e2-2249-4c12-835a-cc623cc8f3ba"),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BookVerse.Api.Entities.Book", b =>
                {
                    b.HasOne("BookVerse.Api.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookVerse.Api.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BookVerse.Api.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BookVerse.Api.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookVerse.Api.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BookVerse.Api.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookVerse.Api.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookVerse.Api.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
